updated permissions sets for read/list secrets from sm
dod-ccpo/atat-web-api pull request #1276
Opened 2022-10-18 17:36 UTC by zachmcclurg-ccpo

updated sso-permissions-sets to include the missing Read/List permission for Secrets Manager.

2022-10-18 17:52 UTC, zachclark-ccpo requested changes

2022-10-18 17:52 UTC, zachclark-ccpo commented on cfn-templates/sso-permission-sets.cf.yaml
> +            Resource: "*"
```suggestion
```
I would delete this statement and not attach to the developer role. 
Developers can use the secret read access instead.

2022-10-18 17:52 UTC, zachclark-ccpo commented on cfn-templates/sso-permission-sets.cf.yaml
> +              - secretsmanager:ListSecrets
```suggestion
          - Effect: Allow
            Action: 
              - secretsmanager:GetSecretValue
              - secretsmanager:ListSecrets
              - secretsmanager:DescribeSecret
```

I would add `DescribeSecret` to this statement: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html

2022-10-21 18:17 UTC, zachclark-ccpo approved these changes

2022-10-25 02:14 UTC, juliusfitzhugh-ccpo approved these changes

2022-11-08 15:43 UTC, jeffsegal-ccpo approved these changes

2022-11-08 15:43 UTC, merged