Share the names of the created IdPs in SSM
dod-ccpo/atat-web-api pull request #205
Opened 2021-09-15 14:56 UTC by kylelaker-ccpo

This is required because the UI repo's stack needs to be able to query
the list of IdPs so that the Cognito User Pool Client can configure them
as the supported IdPs.

This will unblock AT-6532.

2021-09-15 20:33 UTC, jasonburkert-ccpo requested changes
After comparing these PRs side by side, I think this one may need to have the parameter name changed as suggested.
- API: https://github.com/dod-ccpo/atat-web-api/pull/205
- UI: https://github.com/dod-ccpo/atat-web-ui/pull/123

2021-09-15 20:33 UTC, jasonburkert-ccpo commented on infrastructure/lib/atat-auth-stack.ts
> +    const idpNamesParam = new ssm.StringListParameter(this, "CognitoIdPParameter", {
```suggestion
    const idpNamesParam = new ssm.StringListParameter(this, "CognitoIdPNamesParameter", {
```

2021-09-15 21:07 UTC, jasonburkert-ccpo approved these changes

2021-09-16 12:19 UTC, kylelaker-ccpo commented on infrastructure/lib/atat-auth-stack.ts
> +    const idpNamesParam = new ssm.StringListParameter(this, "CognitoIdPParameter", {
Good catch!

2021-09-16 12:24 UTC, kylelaker-ccpo commented
I'm going to go ahead and merge this. Even though the consumer on the UI side isn't quite ready, this sets up an additional parameter. If we end up needing additional data, we can always fix it in another PR later.

2021-09-16 12:24 UTC, merged