AT-7049: New OpenAPI specification for provisioning
dod-ccpo/atat-web-api pull request #596
Opened 2022-02-02 16:56 UTC by jeffsegal-ccpo

Defines a new OpenAPI specification which will be used to allow external machine interfaces (initially just SNOW) to invoke provisioning operations in our AWS infrastructure. This will support the following use cases:

- Adding new accounts
- Adding funding sources to existing accounts
- Adding operators to existing accounts

It will be tied very closely to the public ATAT spec that the CSPs will implement and share some data structures (in the future we could look at cleaner ways to do so), but it won't necessarily be a 1:1 copy. It is fairly simple for now, but if we add more capability to the public spec, that will need to be reflected here as well.

2022-02-03 20:05 UTC, jeffsegal-ccpo commented on atat_provisioning_api.yaml
> +            example: "user@mail.mil"
Not at all silly. That was part of the effort to simplify the provisioning process. My proposal is that we will simply collect a set of email addresses who will receive full access to the Accounts and call it a day.

2022-02-04 18:16 UTC, jasonburkert-ccpo requested changes
Couple minor suggestions and one about cloud/csp terminology that we spoke about.

2022-02-04 18:16 UTC, jasonburkert-ccpo commented on atat_provisioning_api.yaml
> +    TargetCloud:
As we discussed via call.  Unsure about meaning of _cloud_ vs. _csp_ terminology.

```suggestion
    TargetCloudServiceProvider:
```

2022-02-04 21:25 UTC, jeffsegal-ccpo commented on atat_provisioning_api.yaml
> +        description: An empty String or JSON body
Fixed

2022-02-04 21:26 UTC, jeffsegal-ccpo commented on atat_provisioning_api.yaml
> +          enum: [INVALID_INPUT, OTHER]
Yeah if we're not using it for any sort of automation purposes then it's probably better to leave it out.

2022-02-07 14:52 UTC, jasonburkert-ccpo approved these changes

2022-02-07 14:53 UTC, merged