Add Terraform Scripts To Support Shared Infrastructure
dod-ccpo/atat-web-api pull request #6
Opened 2021-07-06 21:34 UTC by zachclark-ccpo

Created Terraform scripts for shared infrastructure on Azure.
The following resources are created with this implementation:

- Resource group "poc-shared-infrastructure"
- Storage account "pocsharedstorage630"
- Key vault (Standard SKU) "atat-test-1-keyvault"
- 2 Secrets to populate Key vault
- 2 RSA keys to populate Key vault

When you clone this branch for review, make sure to run `terraform init`. 
Refer to the README for additional instructions.

2021-07-08 15:43 UTC, anhtran-ccpo commented
Can you rebase with develop?

2021-07-08 17:21 UTC, anhtran-ccpo approved these changes
Ran the commands described in the README with the tfvars supplied to me and was a success.

2021-07-08 17:52 UTC, zachclark-ccpo commented
There are currently 2 problems:

- You cannot run `terraform apply` if the infrastructure was already deployed remotely by someone else.
- Creating the keyvault locks access to anyone who isn't Tom, Jeff, or the person who ran `terraform apply`.

2021-07-08 17:54 UTC, jasonburkert-ccpo commented
@zachclark-ccpo Why not locked to Tom and Jeff?  Is it due to some role or membership in a group?

2021-07-08 19:16 UTC, jasonburkert-ccpo reviewed
Some minor suggestions.  Waiting to see outcome of the revision.  Hit the first problem @zachclark-ccpo mentioned.

2021-07-09 18:44 UTC, kylelaker-ccpo reviewed
Can we make sure to run `terraform fmt poc/shared_infrastructure/`

2021-07-12 13:45 UTC, zachclark-ccpo commented on poc/shared_infrastructure/main.tf
> +}
Understandable, I'll update the versioning.

2021-07-12 15:21 UTC, zachclark-ccpo commented on poc/shared_infrastructure/variables-auth.tf
> +}
Updated the versions in 618e7aa

2021-07-12 15:22 UTC, zachclark-ccpo commented on poc/shared_infrastructure/main.tf
> +}
Updated config versioning 618e7aa

2021-07-12 18:08 UTC, zachclark-ccpo commented
The 2 problems have been resolved.

2021-07-12 19:23 UTC, kylelaker-ccpo requested changes

2021-07-12 19:23 UTC, kylelaker-ccpo commented on poc/shared_infrastructure/main.tf
> +  required_version = ">= 0.10"
```suggestion
  required_version = ">= 1.0"
```

2021-07-12 19:28 UTC, zachclark-ccpo commented on poc/shared_infrastructure/main.tf
> +  required_version = ">= 0.10"
Understandable, thank you.

2021-07-12 19:40 UTC, kylelaker-ccpo approved these changes

2021-07-12 19:40 UTC, merged