Create IAM Users for Invoking HOTH API
dod-ccpo/atat-web-api pull request #823
Opened 2022-04-27 21:02 UTC by zachclark-ccpo

2022-04-28 15:02 UTC, kylelaker-ccpo requested changes

2022-04-28 15:02 UTC, kylelaker-ccpo commented on lib/constructs/api-user.ts
> +
This is dead code now. Please delete
```suggestion
```

2022-04-28 20:22 UTC, juliusfitzhugh-ccpo commented on lib/constructs/apigateway.ts
> +type HttpMethod = "GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "OPTIONS";
There is an `HttpMethod` `enum` defined in `lib/http.ts`  that might be able to be used here if an `enum` is okay to use here.

2022-04-29 14:12 UTC, zachclark-ccpo commented on lib/constructs/apigateway.ts
> +        authorizationType: apigw.AuthorizationType.IAM,
Commented this section out.

2022-04-29 21:18 UTC, kylelaker-ccpo approved these changes

2022-04-29 21:20 UTC, merged