AT:7491 - Ensuring all resources are attached to a VPC as necessary
dod-ccpo/atat-web-api pull request #889
Opened 2022-05-25 18:23 UTC by jeffsegal-ccpo

This change leverages the existing `network` parameter and pushes it down to be available to use when creating `NodeJsFunction` instances such that they include a `vpc` and `vpcSubnets` property if the given environment includes a Network stack (and thus `network` is defined). 

Ticket: AT-7491

2022-05-26 15:15 UTC, kylelaker-ccpo commented
This seems reasonable. Did you happen to test by modifying the pipeline stack to pass down the `network` prop?

2022-05-26 20:34 UTC, kylelaker-ccpo requested changes
So the more I think about this, the more I want to make sure that we're generally following a pattern of not passing "bigger" construct types around.

So literals/primitives/resolvables, constructs, and stacks can get passed to stacks and apps but Constructs should only ever have literals/primitives/resolvables passed to them (so let's not pass a stack to a construct).

2022-05-26 20:46 UTC, jeffsegal-ccpo commented on lib/constructs/api-sfn-function.ts
> +  readonly network?: AtatNetStack;
Fixed

2022-06-16 13:36 UTC, jasonburkert-ccpo commented
My understanding is that this will not be merged until the completion of AT-7326 in order to keep dev API accessible.

2022-07-27 22:19 UTC, kylelaker-ccpo approved these changes
Most of this has been done in other tickets at this point. I have cleaned this up a bit and simplified it to work in the updated code base. In all, the adjustments are pretty trivial.

2022-07-27 22:19 UTC, merged