Implement 'deleteTaskOrderFile` function
dod-ccpo/atat-web-api pull request #93
Opened 2021-08-18 19:14 UTC by zachclark-ccpo

### Overview
Ticket: AT-6418

### TODO

- [ ] add 404 response if nothing is deleted
- [ ] write tests

2021-08-18 21:13 UTC, jeffsegal-ccpo requested changes

2021-08-18 21:13 UTC, jeffsegal-ccpo commented on packages/api/taskOrderFiles/deleteTaskOrderFile.ts
> +  const taskOrderNumber = event.pathParameters?.taskOrderNumber;
We updated the API a little while back to generate this ID ourselves, so it should be `taskOrderId` instead.

2021-08-18 21:13 UTC, jeffsegal-ccpo commented on packages/api/taskOrderFiles/deleteTaskOrderFile.ts
> +  { code: ErrorCodes.INVALID_INPUT, message: "TaskOrderNumber must be specified in the URL path" },
`taskOrderId`

2021-08-18 21:13 UTC, jeffsegal-ccpo commented on packages/api/taskOrderFiles/deleteTaskOrderFile.ts
> +    Key: taskOrderNumber,
`taskOrderId`

2021-08-18 22:38 UTC, kylelaker commented
What value would be provided by trying to have a strongly consistent API ourselves over an eventually consistent API from AWS? Do we _really_ need to care about returning a 404 here anyway? Fundamentally, you just want to know whether the delete completed successfully or not where that is defined by whether object is expected to still exist or not. Seems weird for two DELETEs in a row to have to return different status codes when the user probably doesn't really care. They just want to make sure it's not a 400 or 500.

2021-08-19 13:55 UTC, jeffsegal-ccpo approved these changes

2021-08-19 14:02 UTC, kylelaker-ccpo approved these changes

2021-08-19 14:02 UTC, merged